kind: Secret
apiVersion: v1
metadata:
  name: router-proxy-vpnclient-secret
data:
  tls.crt: {{ pki "openvpn-router-proxy-client.crt" }}
  tls.key: {{ pki "openvpn-router-proxy-client.key" }}
  ca.crt: {{ pki "openvpn-ca.crt" }}
