kind: Secret
apiVersion: v1
metadata:
  name: {{ .file }}-tls
data:
  {{ .secret }}.crt: {{ pki (print .file ".crt") }}
  {{ .secret }}.key: {{ pki (print .file ".key") }}
  {{ .secret }}-ca.crt: {{ pki "root-ca.crt" }}
