apiVersion: v1
kind: Secret
metadata:
  name: kube-controller-manager
data:
  kubeconfig: {{ pki "internal-admin.kubeconfig" }}
  service-account.key: {{ pki "service-account.key" }}
  cluster-signer.crt: {{ pki "cluster-signer.crt" }}
  cluster-signer.key: {{ pki "cluster-signer.key" }}
