apiVersion: v1
kind: Secret
metadata:
  name: oauth-openshift
data:
  kubeconfig: {{ pki "internal-admin.kubeconfig" }}
  server.crt: {{ pki "ingress-openshift.crt" }}
  server.key: {{ pki "ingress-openshift.key" }}
