
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: hypershift-operator-role
rules:
- apiGroups:
  - hypershift.openshift.io
  resources:
  - openshiftclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hypershift.openshift.io
  resources:
  - openshiftclusters/status
  verbs:
  - get
  - patch
  - update
