apiVersion: v1
kind: Service
metadata:
  name: oauth-openshift
spec:
  selector:
    app: oauth-openshift
  ports:
  - name: https
    port: 443
    targetPort: 6443
    nodePort: {{ .ExternalOauthPort }}
  type: NodePort
