apiVersion: v1
kind: ConfigMap
metadata:
  name: user-manifest-openshift-browser-client
data:
  data: |
    apiVersion: oauth.openshift.io/v1
    grantMethod: auto
    kind: OAuthClient
    metadata:
      name: openshift-browser-client
    redirectURIs:
    - https://{{ .ExternalOauthDNSName }}:{{ .ExternalOauthPort }}/oauth/token/display
    secret: "{{ randomString 32  }}"
