apiVersion: v1
kind: ConfigMap
metadata:
  name: user-manifest-openvpn-client-secret
data:
  data: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: openvpn-client
      namespace: kube-system
    data:
      tls.crt: {{ pki "openvpn-worker-client.crt" }}
      tls.key: {{ pki "openvpn-worker-client.key" }}
      ca.crt: {{ pki "openvpn-ca.crt" }}
