apiVersion: v1
kind: Service
metadata:
  name: openvpn-server
spec:
  ports:
  - port: 1194
    protocol: TCP
    targetPort: 1194
    nodePort: {{ .OpenVPNNodePort }}
  selector:
    app: openvpn-server
  type: NodePort
