kind: Secret
apiVersion: v1
metadata:
  name: kube-apiserver-vpnclient-secret
data:
  tls.crt: {{ pki "openvpn-kube-apiserver-client.crt" }}
  tls.key: {{ pki "openvpn-kube-apiserver-client.key" }}
  ca.crt: {{ pki "openvpn-ca.crt" }}
